name: development
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          registry: docker.pedanticorderliness.com
          username: ${{ secrets.DOCKER_REG_USER }}
          password: ${{ secrets.DOCKER_REG_PASS }}
          repository: gitops-example
          tags: ${{ github.sha }},latest

      - name: Update tag
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          tag=$(cat ./chart/values.yaml | grep tag: | awk '{print $2}')
          sed -i "s/$tag/$git_hash/" ./chart/values.yaml

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Tag updated
